export interface RuleDefinition {
  id: string;
  regime: string;
  obligationType: string;
  name: string;
  statutoryBasis: string;
  triggerCondition: string;
  dateCalcLogic: string;
  internalTargetOffsetDays: number;
  recurrence: string;
  effectiveFrom: string;
  effectiveTo?: string;
  active: boolean;
  warningFlag?: boolean;
  notes?: string;
}

export const RULES: RuleDefinition[] = [
  // ── Corporation Tax ──────────────────────────────────────────────────────
  {
    id: "CT-FILING",
    regime: "Corporation Tax",
    obligationType: "Filing",
    name: "CT600 Corporation Tax return",
    statutoryBasis: "S455 CTA 2010; FA 1998 Schedule 18",
    triggerCondition: "CT return required = Yes AND accounting period end is set",
    dateCalcLogic: "Filing deadline = 12 months after accounting period end",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "2000-01-01",
    active: true,
  },
  {
    id: "CT-PAYMENT-STD",
    regime: "Corporation Tax Payment",
    obligationType: "Payment",
    name: "Corporation Tax payment (standard — not QIP)",
    statutoryBasis: "S59 TMA 1970; CTSA regime",
    triggerCondition: "CT return required = Yes AND large company = No AND very large company = No",
    dateCalcLogic: "Payment deadline = 9 months and 1 day after accounting period end",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "2000-01-01",
    active: true,
  },

  // ── Quarterly Instalment Payments — Large company ───────────────────────
  {
    id: "QIP-L-1",
    regime: "Quarterly Instalment Payments",
    obligationType: "Payment",
    name: "QIP Instalment 1 (large company)",
    statutoryBasis: "SI 1998/3175 Corporation Tax (Instalment Payments) Regulations reg 5",
    triggerCondition: "Large company = Yes AND very large company = No AND accounting period start and end are set",
    dateCalcLogic: "14th day of the 7th month from the start of the accounting period (i.e. 6 months + 14 days from AP start)",
    internalTargetOffsetDays: 7,
    recurrence: "Annual",
    effectiveFrom: "1998-10-01",
    active: true,
    warningFlag: true,
    notes: "Instalments apply to companies whose CT liability in the previous period exceeded £10,000 (or £50,000 for small profits rate). Verify threshold with tax adviser.",
  },
  {
    id: "QIP-L-2",
    regime: "Quarterly Instalment Payments",
    obligationType: "Payment",
    name: "QIP Instalment 2 (large company)",
    statutoryBasis: "SI 1998/3175 reg 5",
    triggerCondition: "Large company = Yes AND very large company = No AND accounting period start and end are set",
    dateCalcLogic: "14th day of the 10th month from the start of the accounting period",
    internalTargetOffsetDays: 7,
    recurrence: "Annual",
    effectiveFrom: "1998-10-01",
    active: true,
    warningFlag: true,
  },
  {
    id: "QIP-L-3",
    regime: "Quarterly Instalment Payments",
    obligationType: "Payment",
    name: "QIP Instalment 3 (large company)",
    statutoryBasis: "SI 1998/3175 reg 5",
    triggerCondition: "Large company = Yes AND very large company = No AND accounting period start and end are set",
    dateCalcLogic: "14th day of the 13th month from the start of the accounting period (14 days after AP end for 12-month period)",
    internalTargetOffsetDays: 7,
    recurrence: "Annual",
    effectiveFrom: "1998-10-01",
    active: true,
    warningFlag: true,
  },
  {
    id: "QIP-L-4",
    regime: "Quarterly Instalment Payments",
    obligationType: "Payment",
    name: "QIP Instalment 4 (large company)",
    statutoryBasis: "SI 1998/3175 reg 5",
    triggerCondition: "Large company = Yes AND very large company = No AND accounting period start and end are set",
    dateCalcLogic: "14th day of the 16th month from the start of the accounting period (3 months + 14 days after AP end)",
    internalTargetOffsetDays: 7,
    recurrence: "Annual",
    effectiveFrom: "1998-10-01",
    active: true,
    warningFlag: true,
  },

  // ── Quarterly Instalment Payments — Very large company ──────────────────
  {
    id: "QIP-VL-1",
    regime: "Quarterly Instalment Payments",
    obligationType: "Payment",
    name: "QIP Instalment 1 (very large company — accelerated)",
    statutoryBasis: "SI 1998/3175 reg 5B (very large companies)",
    triggerCondition: "Very large company = Yes AND accounting period start and end are set",
    dateCalcLogic: "14th day of the 3rd month from the start of the accounting period (accelerated schedule)",
    internalTargetOffsetDays: 7,
    recurrence: "Annual",
    effectiveFrom: "2019-04-01",
    active: true,
    warningFlag: true,
    notes: "Very large company threshold: CT liability > £20m (or divided by group members). Verify with tax adviser.",
  },
  {
    id: "QIP-VL-2",
    regime: "Quarterly Instalment Payments",
    obligationType: "Payment",
    name: "QIP Instalment 2 (very large company — accelerated)",
    statutoryBasis: "SI 1998/3175 reg 5B",
    triggerCondition: "Very large company = Yes AND accounting period start and end are set",
    dateCalcLogic: "14th day of the 6th month from the start of the accounting period",
    internalTargetOffsetDays: 7,
    recurrence: "Annual",
    effectiveFrom: "2019-04-01",
    active: true,
    warningFlag: true,
  },
  {
    id: "QIP-VL-3",
    regime: "Quarterly Instalment Payments",
    obligationType: "Payment",
    name: "QIP Instalment 3 (very large company — accelerated)",
    statutoryBasis: "SI 1998/3175 reg 5B",
    triggerCondition: "Very large company = Yes AND accounting period start and end are set",
    dateCalcLogic: "14th day of the 9th month from the start of the accounting period",
    internalTargetOffsetDays: 7,
    recurrence: "Annual",
    effectiveFrom: "2019-04-01",
    active: true,
    warningFlag: true,
  },
  {
    id: "QIP-VL-4",
    regime: "Quarterly Instalment Payments",
    obligationType: "Payment",
    name: "QIP Instalment 4 (very large company — accelerated)",
    statutoryBasis: "SI 1998/3175 reg 5B",
    triggerCondition: "Very large company = Yes AND accounting period start and end are set",
    dateCalcLogic: "14th day of the 12th month from the start of the accounting period (14 days after AP end for 12-month period)",
    internalTargetOffsetDays: 7,
    recurrence: "Annual",
    effectiveFrom: "2019-04-01",
    active: true,
    warningFlag: true,
  },

  // ── VAT ──────────────────────────────────────────────────────────────────
  {
    id: "VAT-Q",
    regime: "VAT",
    obligationType: "Filing",
    name: "VAT quarterly return (MTD)",
    statutoryBasis: "VAT Act 1994 s25; SI 1995/2518 reg 25A; SI 2018/261 (Making Tax Digital for VAT)",
    triggerCondition: "VAT registered = Yes AND VAT quarter end month is set",
    dateCalcLogic: "Filing and payment deadline = 7th day of the second month following the VAT quarter end (1 month + 7 days after quarter end)",
    internalTargetOffsetDays: 7,
    recurrence: "Quarterly",
    effectiveFrom: "2019-04-01",
    active: true,
  },

  // ── P11D / P11D(b) ───────────────────────────────────────────────────────
  {
    id: "P11D-FILING",
    regime: "P11D/P11D(b)",
    obligationType: "Filing",
    name: "P11D and P11D(b) filing",
    statutoryBasis: "ITEPA 2003 ss.65, 69, 73; SI 2003/2682 PAYE Regulations reg 85",
    triggerCondition: "P11D required = Yes",
    dateCalcLogic: "6 July following the end of the tax year (5 April)",
    internalTargetOffsetDays: 14,
    recurrence: "Annual",
    effectiveFrom: "2004-04-06",
    active: true,
  },
  {
    id: "P11D-PAYMENT",
    regime: "P11D/P11D(b)",
    obligationType: "Payment",
    name: "P11D(b) Class 1A NIC payment",
    statutoryBasis: "SSCBA 1992 s10; SI 2001/1004 reg 67C",
    triggerCondition: "P11D required = Yes",
    dateCalcLogic: "22 July following the tax year end (19 July for non-electronic payment)",
    internalTargetOffsetDays: 7,
    recurrence: "Annual",
    effectiveFrom: "2004-04-06",
    active: true,
  },

  // ── PSA ──────────────────────────────────────────────────────────────────
  {
    id: "PSA-AGREEMENT",
    regime: "PSA",
    obligationType: "Review",
    name: "PSA agreement / renewal with HMRC",
    statutoryBasis: "SI 1996/2631 reg 109; ITEPA 2003 ss.703–707",
    triggerCondition: "PSA required = Yes",
    dateCalcLogic: "PSA must be agreed with HMRC by 6 July following the end of the tax year",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "1996-04-06",
    active: true,
  },
  {
    id: "PSA-PAYMENT",
    regime: "PSA",
    obligationType: "Payment",
    name: "PSA tax and NIC calculation and payment",
    statutoryBasis: "SI 1996/2631 reg 111",
    triggerCondition: "PSA required = Yes",
    dateCalcLogic: "22 October following the end of the tax year (19 October for non-electronic)",
    internalTargetOffsetDays: 14,
    recurrence: "Annual",
    effectiveFrom: "1996-04-06",
    active: true,
  },

  // ── ERS ──────────────────────────────────────────────────────────────────
  {
    id: "ERS-ANNUAL",
    regime: "ERS",
    obligationType: "Filing",
    name: "ERS annual return",
    statutoryBasis: "ITEPA 2003 s421JA; various ERS scheme regulations",
    triggerCondition: "ERS scheme present = Yes",
    dateCalcLogic: "6 July following the end of the tax year (5 April)",
    internalTargetOffsetDays: 21,
    recurrence: "Annual",
    effectiveFrom: "2014-04-06",
    active: true,
  },

  // ── EMI ──────────────────────────────────────────────────────────────────
  {
    id: "EMI-ANNUAL",
    regime: "EMI",
    obligationType: "Filing",
    name: "EMI annual return",
    statutoryBasis: "ITEPA 2003 Sch 5; ITEPA 2003 s421JA",
    triggerCondition: "EMI scheme present = Yes",
    dateCalcLogic: "6 July following the end of the tax year (5 April) — filed as part of ERS return",
    internalTargetOffsetDays: 21,
    recurrence: "Annual",
    effectiveFrom: "2014-04-06",
    active: true,
  },

  // ── R&D ──────────────────────────────────────────────────────────────────
  {
    id: "RD-NOTIFICATION",
    regime: "R&D",
    obligationType: "R&D claim notification",
    name: "R&D advance claim notification",
    statutoryBasis: "FA 2023 s18; CTA 2009 s1142A",
    triggerCondition: "R&D claim expected = Yes AND R&D notification needed = Yes",
    dateCalcLogic: "6 months after accounting period end (for new claimants or those who have not claimed in the prior 3 years)",
    internalTargetOffsetDays: 60,
    recurrence: "Annual",
    effectiveFrom: "2023-04-01",
    active: true,
    warningFlag: true,
    notes: "Applies to new R&D claimants and those who did not claim R&D in the 3 years prior to this AP. Verify with tax adviser whether notification is required.",
  },
  {
    id: "RD-AIF",
    regime: "R&D",
    obligationType: "R&D additional information form",
    name: "R&D Additional Information Form",
    statutoryBasis: "FA 2023 s18; HMRC R&D Additional Information Form requirements",
    triggerCondition: "R&D claim expected = Yes AND R&D AIF needed = Yes",
    dateCalcLogic: "Must be submitted to HMRC before the CT600 is filed; internal target = 11 months after AP end",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "2023-08-08",
    active: true,
  },
  {
    id: "RD-EVIDENCE",
    regime: "R&D",
    obligationType: "R&D technical evidence pack",
    name: "R&D technical evidence pack",
    statutoryBasis: "HMRC CIRD guidance; R&D relief substantiation best practice",
    triggerCondition: "R&D claim expected = Yes",
    dateCalcLogic: "Internal target: 10 months after AP end (to allow review before CT600)",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "2000-01-01",
    active: true,
  },
  {
    id: "RD-REVIEW",
    regime: "R&D",
    obligationType: "R&D claim review before CT600 submission",
    name: "R&D claim review (pre-CT600)",
    statutoryBasis: "Governance best practice; HMRC CIRD guidance",
    triggerCondition: "R&D claim expected = Yes",
    dateCalcLogic: "Internal target: 11 months after AP end (1 month before CT600 statutory deadline)",
    internalTargetOffsetDays: 14,
    recurrence: "Annual",
    effectiveFrom: "2000-01-01",
    active: true,
  },

  // ── Capital Allowances ───────────────────────────────────────────────────
  {
    id: "CA-CAPEX",
    regime: "Capital Allowances",
    obligationType: "Capital expenditure evidence collection",
    name: "Capital expenditure evidence collection",
    statutoryBasis: "CAA 2001 ss.1–570; Governance best practice",
    triggerCondition: "Capital allowances activity = Yes",
    dateCalcLogic: "Internal target: 8 months after AP end",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "2001-04-01",
    active: true,
  },
  {
    id: "CA-FAR",
    regime: "Capital Allowances",
    obligationType: "Fixed asset register review",
    name: "Fixed asset register review",
    statutoryBasis: "CAA 2001; Governance best practice",
    triggerCondition: "Capital allowances activity = Yes",
    dateCalcLogic: "Internal target: 9 months after AP end",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "2001-04-01",
    active: true,
  },
  {
    id: "CA-AIA",
    regime: "Capital Allowances",
    obligationType: "AIA review",
    name: "AIA / full expensing / special rate review",
    statutoryBasis: "CAA 2001 ss.38A–51O; F(No.2)A 2023 (full expensing permanence)",
    triggerCondition: "Capital allowances activity = Yes",
    dateCalcLogic: "Internal target: 9 months after AP end",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "2001-04-01",
    active: true,
  },
  {
    id: "CA-CT",
    regime: "Capital Allowances",
    obligationType: "Capital allowances position included in CT computation",
    name: "Capital allowances position in CT computation",
    statutoryBasis: "CAA 2001; CTA 2010; Governance best practice",
    triggerCondition: "Capital allowances activity = Yes",
    dateCalcLogic: "Internal target: 11 months after AP end (before CT600 filing)",
    internalTargetOffsetDays: 14,
    recurrence: "Annual",
    effectiveFrom: "2001-04-01",
    active: true,
  },

  // ── SAO ──────────────────────────────────────────────────────────────────
  {
    id: "SAO-EVIDENCE",
    regime: "SAO",
    obligationType: "Evidence preparation",
    name: "SAO evidence preparation",
    statutoryBasis: "FA 2009 Sch 46; HMRC SAO guidance",
    triggerCondition: "SAO in scope = Yes",
    dateCalcLogic: "Internal target: 11 months after AP end",
    internalTargetOffsetDays: 14,
    recurrence: "Annual",
    effectiveFrom: "2009-04-01",
    active: true,
  },
  {
    id: "SAO-CERT",
    regime: "SAO",
    obligationType: "Approval",
    name: "SAO certification",
    statutoryBasis: "FA 2009 Sch 46 para 1; HMRC SAO guidance",
    triggerCondition: "SAO in scope = Yes",
    dateCalcLogic: "12 months after the accounting period end (same as CT600 filing deadline)",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "2009-04-01",
    active: true,
    notes: "SAO is personally liable for a £5,000 penalty per failure. Certificate must be filed with HMRC.",
  },

  // ── Published Tax Strategy ───────────────────────────────────────────────
  {
    id: "PTS-REVIEW",
    regime: "Published Tax Strategy",
    obligationType: "Review",
    name: "Published Tax Strategy internal review",
    statutoryBasis: "FA 2016 Sch 19; HMRC Large Business Tax Strategy guidance",
    triggerCondition: "Published Tax Strategy in scope = Yes",
    dateCalcLogic: "Internal review target: 3 months before accounting period end (to allow time for publication before the period ends)",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "2016-09-15",
    active: true,
  },
  {
    id: "PTS-PUB",
    regime: "Published Tax Strategy",
    obligationType: "Approval",
    name: "Published Tax Strategy publication",
    statutoryBasis: "FA 2016 Sch 19 para 16(3)",
    triggerCondition: "Published Tax Strategy in scope = Yes",
    dateCalcLogic: "Must be published before the end of the financial year (AP end date)",
    internalTargetOffsetDays: 30,
    recurrence: "Annual",
    effectiveFrom: "2016-09-15",
    active: true,
    notes: "First offence penalty: £7,500. Continuing penalties apply. Strategy must be accessible on a UK-facing website.",
  },

  // ── Pillar 2 ─────────────────────────────────────────────────────────────
  {
    id: "P2-PLACEHOLDER",
    regime: "Pillar 2",
    obligationType: "Registration",
    name: "Pillar 2 registration / reporting review (placeholder)",
    statutoryBasis: "Finance (No.2) Act 2023 (Pillar 2 — global minimum tax); HMRC Pillar 2 guidance",
    triggerCondition: "Pillar 2 in scope = Yes",
    dateCalcLogic: "PLACEHOLDER: 15 months after AP end. Pillar 2 reporting dates are still evolving — this date MUST be reviewed and confirmed by a tax owner or adviser.",
    internalTargetOffsetDays: 90,
    recurrence: "Annual",
    effectiveFrom: "2024-01-01",
    active: true,
    warningFlag: true,
    notes: "Pillar 2 applies to MNE groups with consolidated revenue ≥ €750m. Registration and reporting timelines are subject to HMRC guidance updates. Treat all generated dates as indicative only.",
  },
];

export function getRuleById(id: string): RuleDefinition | undefined {
  return RULES.find((r) => r.id === id);
}
