export type ControlledRuleSeed = {
  engineVersion: string;
  ruleKey: string;
  regime: string;
  name: string;
  description: string;
  obligationType: string;
  statutoryBasis: string;
  statutoryUrl: string;
  authorityLevel: "Legislation" | "Statutory notice" | "HMRC manual" | "GOV.UK guidance" | "Draft guidance";
  legalStatus: "Enacted" | "In force" | "Administrative" | "Interim draft";
  triggerDescription: string;
  triggerConfig: Record<string, unknown>;
  calculationKey: string;
  calculationDescription: string;
  recurrence: string;
  effectiveFrom: string;
  humanReviewRequired: boolean;
  changeRationale: string;
  sourceLastCheckedAt: string;
  citations?: Array<{
    title: string;
    url: string;
    authorityLevel: string;
    locator?: string;
  }>;
};

/**
 * Immutable identifier for the deterministic date/applicability code reviewed
 * with these controlled-content records. Changing rule code requires a new
 * identifier and successor rule versions; it must never reinterpret an
 * already-approved content version in place.
 */
export const CONTROLLED_RULE_ENGINE_VERSION = "2026.07.11-1";

type ControlledRuleContent = Omit<ControlledRuleSeed, "engineVersion">;

const checked = "2026-07-11";

/**
 * The built-in UK pack is controlled content. Date arithmetic lives in
 * rule-engine.ts, while these records define the approved source, trigger,
 * effective date and explanation that are stored with every obligation.
 */
const CONTROLLED_RULE_CONTENT: ControlledRuleContent[] = [
  {
    ruleKey: "CT_RETURN",
    regime: "Corporation Tax",
    name: "Company Tax Return (CT600)",
    description: "File a Company Tax Return for each Corporation Tax accounting period.",
    obligationType: "Filing",
    statutoryBasis: "Finance Act 1998, Schedule 18, paragraph 14",
    statutoryUrl: "https://www.legislation.gov.uk/ukpga/1998/36/schedule/18/paragraph/14",
    authorityLevel: "Legislation",
    legalStatus: "Enacted",
    triggerDescription: "A notice to deliver is expected or CT return required is confirmed, and a period end is known.",
    triggerConfig: { all: [{ field: "ctReturnRequired", equals: true }, { field: "accountingPeriodEnd", present: true }] },
    calculationKey: "CT_RETURN",
    calculationDescription: "Latest applicable filing date under FA 1998 Sch 18; long periods of account are split into CT accounting periods but share the period-of-account filing date where applicable.",
    recurrence: "Annual",
    effectiveFrom: "1999-07-01",
    humanReviewRequired: false,
    changeRationale: "Initial controlled version; corrects the legacy single-period and statutory-basis implementation.",
    sourceLastCheckedAt: checked,
    citations: [{ title: "HMRC COTAX manual — company return filing dates", url: "https://www.gov.uk/hmrc-internal-manuals/cotax-manual/com130070", authorityLevel: "HMRC manual", locator: "COM130070" }],
  },
  {
    ruleKey: "CT_PAYMENT_STANDARD",
    regime: "Corporation Tax",
    name: "Corporation Tax payment - non-QIP",
    description: "Pay Corporation Tax for a company not paying by quarterly instalments.",
    obligationType: "Payment",
    statutoryBasis: "Taxes Management Act 1970, section 59D",
    statutoryUrl: "https://www.legislation.gov.uk/ukpga/1970/9/section/59D",
    authorityLevel: "Legislation",
    legalStatus: "Enacted",
    triggerDescription: "CT return required and the company is not classified as large or very large for QIP purposes.",
    triggerConfig: { all: [{ field: "ctReturnRequired", equals: true }, { field: "isLargeCompany", equals: false }, { field: "isVeryLargeCompany", equals: false }] },
    calculationKey: "CT_PAYMENT_STANDARD",
    calculationDescription: "Nine months and one day after each Corporation Tax accounting-period end.",
    recurrence: "Annual",
    effectiveFrom: "1999-07-01",
    humanReviewRequired: false,
    changeRationale: "Initial controlled version.",
    sourceLastCheckedAt: checked,
    citations: [{ title: "GOV.UK — Corporation Tax payment deadline", url: "https://www.gov.uk/prepare-file-annual-accounts-for-limited-company", authorityLevel: "GOV.UK guidance" }],
  },
  {
    ruleKey: "CT_QIP_LARGE",
    regime: "Quarterly Instalment Payments",
    name: "Large-company quarterly instalment payments",
    description: "Track the instalment dates for a company confirmed as large for QIP purposes.",
    obligationType: "Payment",
    statutoryBasis: "Corporation Tax (Instalment Payments) Regulations 1998 (SI 1998/3175)",
    statutoryUrl: "https://www.legislation.gov.uk/uksi/1998/3175/contents",
    authorityLevel: "Legislation",
    legalStatus: "In force",
    triggerDescription: "The entity is marked large, not very large, after considering adjusted profits, associated companies, de minimis and first-period grace.",
    triggerConfig: { all: [{ field: "isLargeCompany", equals: true }, { field: "isVeryLargeCompany", equals: false }] },
    calculationKey: "CT_QIP_LARGE",
    calculationDescription: "For 12 months: 6 months and 13 days after AP start, then every three months, with the final date 3 months and 14 days after AP end; shorter periods use the statutory shortened schedule.",
    recurrence: "Per accounting period",
    effectiveFrom: "2002-07-01",
    humanReviewRequired: true,
    changeRationale: "Initial controlled version; applicability remains a tax-owner confirmation because thresholds and grace depend on facts not calculated by tax-able.",
    sourceLastCheckedAt: checked,
    citations: [{ title: "HMRC — Corporation Tax paying in instalments", url: "https://www.gov.uk/guidance/corporation-tax-paying-in-instalments", authorityLevel: "GOV.UK guidance" }],
  },
  {
    ruleKey: "CT_QIP_VERY_LARGE",
    regime: "Quarterly Instalment Payments",
    name: "Very-large-company accelerated instalment payments",
    description: "Track accelerated instalment dates for a company confirmed as very large.",
    obligationType: "Payment",
    statutoryBasis: "Corporation Tax (Instalment Payments) Regulations 1998, regulation 5B",
    statutoryUrl: "https://www.legislation.gov.uk/uksi/2017/1072/made",
    authorityLevel: "Legislation",
    legalStatus: "In force",
    triggerDescription: "The entity is marked very large after considering the adjusted £20m threshold and associated companies.",
    triggerConfig: { all: [{ field: "isVeryLargeCompany", equals: true }] },
    calculationKey: "CT_QIP_VERY_LARGE",
    calculationDescription: "For 12 months: the 14th day of months 3, 6, 9 and 12; shorter periods use the statutory final-instalment rule.",
    recurrence: "Per accounting period",
    effectiveFrom: "2019-04-01",
    humanReviewRequired: true,
    changeRationale: "Initial controlled version; corrects the legacy large-company timetable used for very-large companies.",
    sourceLastCheckedAt: checked,
    citations: [{ title: "HMRC — paying Corporation Tax as a very large company", url: "https://www.gov.uk/guidance/pay-corporation-tax-if-youre-a-very-large-company", authorityLevel: "GOV.UK guidance" }],
  },
  {
    ruleKey: "VAT_QUARTERLY",
    regime: "VAT",
    name: "Quarterly VAT return and payment",
    description: "File and pay a standard quarterly VAT return.",
    obligationType: "Filing and payment",
    statutoryBasis: "VAT Regulations 1995, regulation 25A",
    statutoryUrl: "https://www.legislation.gov.uk/uksi/1995/2518/regulation/25A",
    authorityLevel: "Legislation",
    legalStatus: "In force",
    triggerDescription: "The entity is VAT registered and a standard quarterly stagger is recorded.",
    triggerConfig: { all: [{ field: "vatRegistered", equals: true }, { field: "vatQuarterEndMonth", present: true }] },
    calculationKey: "VAT_QUARTERLY",
    calculationDescription: "One calendar month and seven days after the VAT period end, subject to non-standard schemes and HMRC directions.",
    recurrence: "Quarterly",
    effectiveFrom: "2019-04-01",
    humanReviewRequired: true,
    changeRationale: "Initial controlled version; non-standard VAT periods remain review-required.",
    sourceLastCheckedAt: checked,
    citations: [{ title: "HMRC — submit a VAT return", url: "https://www.gov.uk/submit-vat-return", authorityLevel: "GOV.UK guidance" }],
  },
  {
    ruleKey: "P11D_RETURN",
    regime: "Benefits in kind",
    name: "P11D and P11D(b) reporting",
    description: "Report non-payrolled benefits and the employer Class 1A NIC position.",
    obligationType: "Filing",
    statutoryBasis: "Income Tax (PAYE) Regulations 2003 and Social Security (Contributions) Regulations 2001",
    statutoryUrl: "https://www.legislation.gov.uk/uksi/2003/2682/contents",
    authorityLevel: "Legislation",
    legalStatus: "In force",
    triggerDescription: "P11D reporting is marked required; future periods are reviewed against the phased mandatory-payrolling transition.",
    triggerConfig: { all: [{ field: "p11dRequired", equals: true }] },
    calculationKey: "P11D_RETURN",
    calculationDescription: "6 July after the tax year; from 2027/28 the result is review-required because mandatory payrolling is phased by benefit type and remains interim guidance.",
    recurrence: "Annual",
    effectiveFrom: "2003-04-06",
    humanReviewRequired: false,
    changeRationale: "Initial controlled version with an explicit 2027/28 transition review.",
    sourceLastCheckedAt: checked,
    citations: [
      { title: "HMRC — expenses and benefits deadlines", url: "https://www.gov.uk/employer-reporting-expenses-benefits/deadlines", authorityLevel: "GOV.UK guidance" },
      { title: "Social Security (Contributions) Regulations 2001", url: "https://www.legislation.gov.uk/uksi/2001/1004/contents", authorityLevel: "Legislation" },
    ],
  },
  {
    ruleKey: "P11D_TRANSITION_2027",
    regime: "Benefits in kind",
    name: "April 2027 benefits-in-kind transition impact review",
    description: "Review the intended mandatory-payrolling transition without silently activating draft requirements.",
    obligationType: "Regulatory impact review",
    statutoryBasis: "HMRC interim guidance; final legislation and guidance pending",
    statutoryUrl: "https://www.gov.uk/guidance/draft-guidance-and-legislation-to-aid-preparation-for-reporting-benefits-in-kind-in-real-time/getting-ready-for-mandatory-payrolling-of-benefits-in-kind",
    authorityLevel: "Draft guidance",
    legalStatus: "Interim draft",
    triggerDescription: "A benefits reporting period begins on or after 6 April 2027.",
    triggerConfig: { all: [{ field: "taxYearStart", onOrAfter: "2027-04-06" }] },
    calculationKey: "P11D_TRANSITION_2027",
    calculationDescription: "Create an impact review only; do not activate a statutory filing obligation from interim material.",
    recurrence: "Regulatory change",
    effectiveFrom: "2027-04-06",
    humanReviewRequired: true,
    changeRationale: "Separates interim regulatory change analysis from current P11D obligations.",
    sourceLastCheckedAt: checked,
  },
  {
    ruleKey: "PSA_AGREEMENT",
    regime: "PAYE Settlement Agreement",
    name: "PSA application or amendment",
    description: "Put a new or amended enduring PSA in place when required.",
    obligationType: "Agreement",
    statutoryBasis: "Income Tax (PAYE) Regulations 2003, Part 6",
    statutoryUrl: "https://www.legislation.gov.uk/uksi/2003/2682/part/6",
    authorityLevel: "Legislation",
    legalStatus: "In force",
    triggerDescription: "PSA is relevant and the recorded agreement is not enduring or needs amendment.",
    triggerConfig: { all: [{ field: "psaRequired", equals: true }], any: [{ field: "psaAgreementStatus", equals: "Not in place" }, { field: "psaAgreementStatus", equals: "Amendment needed" }] },
    calculationKey: "PSA_AGREEMENT",
    calculationDescription: "No later than 5 July following the first/relevant tax year; an enduring agreement is not renewed annually.",
    recurrence: "Event-driven",
    effectiveFrom: "2018-04-06",
    humanReviewRequired: true,
    changeRationale: "Initial controlled version; removes the incorrect annual PSA renewal assumption.",
    sourceLastCheckedAt: checked,
    citations: [{ title: "HMRC PSA manual — application and deadlines", url: "https://www.gov.uk/hmrc-internal-manuals/paye-settlement-agreements/psa1150", authorityLevel: "HMRC manual", locator: "PSA1150" }],
  },
  {
    ruleKey: "PSA_CALCULATION",
    regime: "PAYE Settlement Agreement",
    name: "Annual PSA calculation submission",
    description: "Prepare and submit the annual PSA calculation for an enduring agreement.",
    obligationType: "Calculation submission",
    statutoryBasis: "HMRC Guidelines for Compliance GfC1",
    statutoryUrl: "https://www.gov.uk/government/publications/gfc1-2022-guidelines-for-compliance-help-with-paye-settlement-agreement-calculations/gfc1-2022-help-with-paye-settlement-agreements-psa",
    authorityLevel: "GOV.UK guidance",
    legalStatus: "Administrative",
    triggerDescription: "A PSA is relevant and an agreement is recorded as enduring or awaiting amendment.",
    triggerConfig: { all: [{ field: "psaRequired", equals: true }] },
    calculationKey: "PSA_CALCULATION",
    calculationDescription: "HMRC asks employers to send the calculation by 31 July after the tax year.",
    recurrence: "Annual",
    effectiveFrom: "2018-04-06",
    humanReviewRequired: false,
    changeRationale: "Initial controlled version.",
    sourceLastCheckedAt: checked,
  },
  {
    ruleKey: "PSA_PAYMENT",
    regime: "PAYE Settlement Agreement",
    name: "PSA tax and Class 1B NIC payment",
    description: "Pay the annual PSA tax and Class 1B NIC liability.",
    obligationType: "Payment",
    statutoryBasis: "Income Tax (PAYE) Regulations 2003",
    statutoryUrl: "https://www.legislation.gov.uk/uksi/2003/2682/part/6",
    authorityLevel: "Legislation",
    legalStatus: "In force",
    triggerDescription: "A PSA is relevant for the tax year.",
    triggerConfig: { all: [{ field: "psaRequired", equals: true }] },
    calculationKey: "PSA_PAYMENT",
    calculationDescription: "19 October, or 22 October where paid by an approved electronic method, after the tax year.",
    recurrence: "Annual",
    effectiveFrom: "2003-04-06",
    humanReviewRequired: false,
    changeRationale: "Initial controlled version.",
    sourceLastCheckedAt: checked,
    citations: [{ title: "HMRC PSA manual — payment deadlines", url: "https://www.gov.uk/hmrc-internal-manuals/paye-settlement-agreements/psa1150", authorityLevel: "HMRC manual", locator: "PSA1150" }],
  },
  {
    ruleKey: "ERS_RETURN",
    regime: "Employment-Related Securities",
    name: "ERS annual return",
    description: "File the annual ERS return, including nil returns where a registered scheme remains open.",
    obligationType: "Filing",
    statutoryBasis: "ITEPA 2003, section 421JA and scheme regulations",
    statutoryUrl: "https://www.legislation.gov.uk/ukpga/2003/1/section/421JA",
    authorityLevel: "Legislation",
    legalStatus: "In force",
    triggerDescription: "An ERS scheme is recorded for the entity.",
    triggerConfig: { all: [{ field: "hasErs", equals: true }] },
    calculationKey: "ERS_RETURN",
    calculationDescription: "6 July after the tax year.",
    recurrence: "Annual",
    effectiveFrom: "2015-04-06",
    humanReviewRequired: false,
    changeRationale: "Initial controlled version.",
    sourceLastCheckedAt: checked,
    citations: [{ title: "HMRC — submit an ERS end-of-year report", url: "https://www.gov.uk/guidance/submit-your-end-of-year-report-for-employee-share-schemes", authorityLevel: "GOV.UK guidance" }],
  },
  {
    ruleKey: "RD_NOTIFICATION",
    regime: "R&D relief",
    name: "R&D claim notification",
    description: "Notify HMRC of an intended R&D claim where the notification condition is met.",
    obligationType: "Notification",
    statutoryBasis: "CTA 2009, section 1142A; SI 2023/813",
    statutoryUrl: "https://www.legislation.gov.uk/ukpga/2009/4/section/1142A",
    authorityLevel: "Legislation",
    legalStatus: "In force",
    triggerDescription: "An R&D claim is expected and the tax owner has confirmed that advance notification is required.",
    triggerConfig: { all: [{ field: "rdClaimExpected", equals: true }, { field: "rdNotificationNeeded", equals: true }] },
    calculationKey: "RD_NOTIFICATION",
    calculationDescription: "Six months after the end of the period of account; a long period has one notification window across its CT accounting periods.",
    recurrence: "Per period of account",
    effectiveFrom: "2023-04-01",
    humanReviewRequired: true,
    changeRationale: "Initial controlled version; applicability depends on prior claim history.",
    sourceLastCheckedAt: checked,
    citations: [
      { title: "R&D claim notification regulations", url: "https://www.legislation.gov.uk/uksi/2023/813/contents/made", authorityLevel: "Legislation" },
      { title: "HMRC — tell HMRC about a planned R&D claim", url: "https://www.gov.uk/guidance/tell-hmrc-that-youre-planning-to-claim-research-and-development-rd-tax-relief", authorityLevel: "GOV.UK guidance" },
    ],
  },
  {
    ruleKey: "RD_AIF",
    regime: "R&D relief",
    name: "R&D additional information form",
    description: "Submit the R&D additional information form before the related Company Tax Return.",
    obligationType: "Pre-filing form",
    statutoryBasis: "Finance Act 1998, Schedule 18, paragraph 83EA; SI 2023/813",
    statutoryUrl: "https://www.legislation.gov.uk/ukpga/1998/36/schedule/18/paragraph/83EA",
    authorityLevel: "Legislation",
    legalStatus: "In force",
    triggerDescription: "An R&D claim and additional information form are recorded as expected.",
    triggerConfig: { all: [{ field: "rdClaimExpected", equals: true }, { field: "rdAifNeeded", equals: true }] },
    calculationKey: "RD_AIF",
    calculationDescription: "Must precede the related CT600; the generated target is one month before the controlled CT filing date and remains an internal target.",
    recurrence: "Per CT accounting period",
    effectiveFrom: "2023-08-08",
    humanReviewRequired: true,
    changeRationale: "Initial controlled version; distinguishes the statutory sequence from an internal target date.",
    sourceLastCheckedAt: checked,
    citations: [
      { title: "R&D additional information regulations", url: "https://www.legislation.gov.uk/uksi/2023/813/contents/made", authorityLevel: "Legislation" },
      { title: "HMRC — submit R&D additional information", url: "https://www.gov.uk/guidance/submit-detailed-information-before-you-claim-research-and-development-rd-tax-relief", authorityLevel: "GOV.UK guidance" },
    ],
  },
  {
    ruleKey: "PILLAR2_SCOPE",
    regime: "Pillar 2",
    name: "Pillar 2 statutory scope assessment",
    description: "Assess the strict-exceeds, day-adjusted two-of-four consolidated revenue test.",
    obligationType: "Scope review",
    statutoryBasis: "Finance (No. 2) Act 2023, section 129",
    statutoryUrl: "https://www.legislation.gov.uk/ukpga/2023/30/section/129",
    authorityLevel: "Legislation",
    legalStatus: "Enacted",
    triggerDescription: "A UK entity or group may be within UK multinational or domestic top-up tax.",
    triggerConfig: { all: [{ field: "hasUkEntity", equals: true }], factsRequired: ["fourPriorPeriods", "consolidatedRevenueEur"] },
    calculationKey: "PILLAR2_SCOPE",
    calculationDescription: "Revenue must strictly exceed €750m adjusted for days in at least two of four prior accounting periods.",
    recurrence: "Per accounting period",
    effectiveFrom: "2023-12-31",
    humanReviewRequired: true,
    changeRationale: "Makes statutory scope evidence an explicit controlled judgement rather than a boolean guess.",
    sourceLastCheckedAt: checked,
  },
  {
    ruleKey: "PILLAR2_REGISTRATION",
    regime: "Pillar 2",
    name: "Pillar 2 registration",
    description: "Register the qualifying group for UK Pillar 2 top-up taxes.",
    obligationType: "Registration",
    statutoryBasis: "Finance (No. 2) Act 2023; Pillar 2 registration notice 1",
    statutoryUrl: "https://www.gov.uk/government/publications/pillar-2-top-up-taxes-registration-notice-1",
    authorityLevel: "Statutory notice",
    legalStatus: "In force",
    triggerDescription: "The group is confirmed in scope and this is its first reporting period.",
    triggerConfig: { all: [{ field: "hasPillar2", equals: true }, { field: "pillar2FirstReportingPeriod", equals: true }] },
    calculationKey: "PILLAR2_REGISTRATION",
    calculationDescription: "Six months after the end of the accounting period in which the group first became qualifying.",
    recurrence: "Once",
    effectiveFrom: "2023-12-31",
    humanReviewRequired: true,
    changeRationale: "Initial controlled version.",
    sourceLastCheckedAt: checked,
  },
  {
    ruleKey: "PILLAR2_RETURN",
    regime: "Pillar 2",
    name: "Pillar 2 UK return and GIR/ORN",
    description: "Submit the UK self-assessment return plus the GIR or overseas return notification.",
    obligationType: "Filing",
    statutoryBasis: "Finance (No. 2) Act 2023, Schedule 14; submission notice 3",
    statutoryUrl: "https://www.gov.uk/government/publications/pillar-2-top-up-taxes-submission-of-returns-notice-3/notice-3-pillar-2-top-up-taxes-submission-of-returns",
    authorityLevel: "Statutory notice",
    legalStatus: "In force",
    triggerDescription: "The group is confirmed in scope for Pillar 2 top-up taxes.",
    triggerConfig: { all: [{ field: "hasPillar2", equals: true }] },
    calculationKey: "PILLAR2_RETURN",
    calculationDescription: "18 months after the first in-scope period end, then 15 months; never earlier than 30 June 2026 for transitional periods.",
    recurrence: "Annual",
    effectiveFrom: "2023-12-31",
    humanReviewRequired: true,
    changeRationale: "Initial controlled version; replaces the former generic 15-month placeholder.",
    sourceLastCheckedAt: checked,
  },
  {
    ruleKey: "PILLAR2_PAYMENT",
    regime: "Pillar 2",
    name: "Pillar 2 top-up tax payment",
    description: "Pay UK domestic or multinational top-up tax for the reporting period.",
    obligationType: "Payment",
    statutoryBasis: "Finance (No. 2) Act 2023 and HMRC payment guidance",
    statutoryUrl: "https://www.gov.uk/guidance/pay-pillar-2-top-up-taxes-domestic-top-up-tax-and-multinational-top-up-tax",
    authorityLevel: "GOV.UK guidance",
    legalStatus: "Administrative",
    triggerDescription: "A qualifying group has a UK Pillar Two payment liability.",
    triggerConfig: { all: [{ field: "hasPillar2", equals: true }, { field: "hasPaymentLiability", equals: true }] },
    calculationKey: "PILLAR2_PAYMENT",
    calculationDescription: "Same first-period 18-month or subsequent 15-month deadline, subject to the 30 June 2026 transitional floor.",
    recurrence: "Annual",
    effectiveFrom: "2023-12-31",
    humanReviewRequired: true,
    changeRationale: "Separates filing and payment evidence while retaining the common statutory timetable.",
    sourceLastCheckedAt: checked,
  },
];

export const CONTROLLED_RULE_DEFINITIONS: ControlledRuleSeed[] =
  CONTROLLED_RULE_CONTENT.map((definition) => ({
    ...definition,
    engineVersion: CONTROLLED_RULE_ENGINE_VERSION,
  }));
